// Notes/Hunger Saviour/hunger-saviour-portal-angular-main/src/app/dashboard/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { RestaurantMenu } from 'src/app/model/RestaurantMenu';
import { CartService } from './services/cart.service';
import { AuthService } from 'src/app/services/auth.service';
import { Order } from 'src/app/model/Order';
import { HttpClient } from '@angular/common/http';
declare var Razorpay: any;

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss']
})
export class CartComponent implements OnInit {
  cartItems: RestaurantMenu[] = [];
  totalCartPrice: number = 0;

  constructor(private cartService: CartService, private router: Router,
    private authService: AuthService, private httpClient: HttpClient) {}

  ngOnInit(): void {
    // Initialize cart items from sessionStorage
    this.cartItems = this.cartService.cartItems;
    this.updateTotalPrice();
  }

  removeFromCart(item: RestaurantMenu) {
    this.cartService.removeFromCart(item);
    this.cartItems = this.cartService.cartItems; // Update cart items after removal
    this.updateTotalPrice();
  }

  increaseQuantity(item: RestaurantMenu) {
    item.quantity = item.quantity ? item.quantity + 1 : 1;
    this.cartService.updateCart(item);
    this.cartItems = this.cartService.cartItems; // Update cart items after quantity increase
    this.updateTotalPrice();
  }

  decreaseQuantity(item: RestaurantMenu) {
    if (item.quantity && item.quantity > 1) {
      item.quantity--;
      this.cartService.updateCart(item);
      this.cartItems = this.cartService.cartItems; // Update cart items after quantity decrease
      this.updateTotalPrice();
    } else if (item.quantity === 1) {
      this.removeFromCart(item);
    }
  }

  updateTotalPrice() {
    this.totalCartPrice = this.cartItems.reduce(
      (total, item) => total + item.price * (item.quantity || 0),
      0
    );
  }

  calculateItemPrice(item: RestaurantMenu): number {
    return item.price * (item.quantity || 1);
  }

  payNow() {
    const RozarpayOptions: any = {
      description: 'Sample Razorpay demo',
      currency: 'INR',
      amount: this.totalCartPrice * 100,
      name: 'Hunger Saviour',
      key: 'rzp_test_Mp5DjD6SGoo7Fk',
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPp1ohLNn2RGU2lTyfORSITnkv7U8Jci4oCa-5T1DfFc5JpagoQkZ6imLo-_vrE3aJw10&usqp=CAUhttps://i.imgur.com/FApqk3D.jpeg',
      prefill: {
        name: 'Srinivas Basha',
        email: 'dssrinivas02@gmail.com',
        phone: '6303010397',
      },
      theme: {
        color: '#14213d',
      },
      modal: {
        ondismiss: () => {
          console.log('dismissed');
        },
      },
    };

    // success callback
    const callback = (paymentid: any) => {
      this.router.navigate(['dashboard/cart']);
      console.log(paymentid);
      console.log(this.authService.getUsername());
      const orderData: Order = {
        username: this.authService.getUsername(),
        totalPrice: this.totalCartPrice,
        transactionId: paymentid.razorpay_payment_id,
        orderJson: JSON.stringify(this.cartItems)
      }
      //call payment service to insert the data(payment id, restaurant json) in payments table
      // From the payment service, we need to write KafkaPublisher to send the data to order service
      // Orderservice will have the listener to get the order data including txnid, order data, username, totalprice
      console.log('calling payment api');
      this.httpClient
          .post('http://localhost:8765/payments', orderData)
          .subscribe({
            next: v => console.log("Payment Done Successfully")
          });
      this.cartItems = [];
      this.cartService.clearCart();
    };
    
    // failure callback(Home work)
    const errorCallback = (error: any) => {
      console.error('Payment failed or error:', error);
      this.router.navigate(['dashboard/cart']);

    };
    RozarpayOptions['handler'] = callback.bind(this);
    const rzp = new Razorpay(RozarpayOptions);
    rzp.on('payment.failed', errorCallback);
    rzp.open();
  }
}


<ng-container *ngIf="cartItems && cartItems.length > 0; else emptyCart">
    <div *ngFor="let item of cartItems" class="d-flex flex-wrap align-items-center justify-content-center my-3">
        <div class="card-image-container col-lg-2 mx-2">
            <img mat-card-image [src]="item.menuImageUrl" alt="{{ item.menuImageUrl }}" />
        </div>
        <div class="col-lg-2 d-flex flex-column align-items-left">
            <div class="fw-bolder text-truncate">{{ item.itemName }}</div>
            <div class="d-flex flex-row fw-bold">
                <mat-icon class="ratingicon">stars</mat-icon>4.2
            </div>
            <div class="fw-bolder">₹{{ item.price }}</div>
        </div>
        <div class="item-quantity col-lg-2">
            <button mat-raised-button color="primary" class="fw-bold text-light m-2" (click)="decreaseQuantity(item)">
                -
            </button>
            <span class="quantity">{{ item.quantity }}</span>
            <button mat-raised-button color="primary" class="fw-bold text-light m-2" (click)="increaseQuantity(item)">
                +
            </button>
        </div>
        <div class="item-price fw-bold col-lg-2">
            Total Price: Rs.{{ calculateItemPrice(item).toFixed(2) }}
        </div>

        <div class="item-actions col-lg-2">
            <button mat-icon-button (click)="removeFromCart(item)">
                <mat-icon class="deleteicon">delete</mat-icon>
            </button>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <button mat-raised-button color="primary" class="fw-bold text-light m-2" (click)="payNow()">
            Checkout
        </button>
    </div>
</ng-container>
<ng-template #emptyCart>
    <div class="d-flex align-items-center justify-content-center mt-5 pt-4">
        <mat-card class="restaurant-card shadow">
            <img mat-card-image [src]="'https://www.vhv.rs/dpng/d/521-5212497_empty-cart-hd-png-download.png'" alt="Restaurant Photo">
        </mat-card>
    </div>
</ng-template>

// Notes/Hunger Saviour/hunger-saviour-portal-react-main/src/components/Cart.js
import React from 'react';
import { useAppContext } from '../AppContext';
import '../index.css';
import { useUsernameContext } from '../UsernameContext';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';

function Cart() {
  const { state, setState } = useAppContext();
  const { username } = useUsernameContext();
  const navigate = useNavigate();

  const clearCart = () => {
    // Reset the cart to an empty array
    setState(prevState => ({
      ...prevState,
      cart: []
    }));
  };

  const removeFromCart = (menuItem) => {
    const updatedCart = state.cart.filter(item => item.menuItem !== menuItem.menuItem);
    setState(prevState => ({
      ...prevState,
      cart: updatedCart
    }));
  };

  const increaseQuantity = (menuItem) => {
    setState(prevState => ({
      ...prevState,
      cart: prevState.cart.map(cartItem =>
        cartItem.menuItem === menuItem.menuItem
          ? { ...cartItem, quantity: cartItem.quantity + 1 }
          : cartItem
      )
    }));
  };

  const decreaseQuantity = (menuItem) => {
    const existingItem = state.cart.find(item => item.menuItem === menuItem.menuItem);
    if (existingItem && existingItem.quantity === 1) {
      // If quantity is 1, remove the item from the cart
      removeFromCart(menuItem);
    } else {
      setState(prevState => ({
        ...prevState,
        cart: prevState.cart.map(cartItem =>
          cartItem.menuItem === menuItem.menuItem && cartItem.quantity > 1
            ? { ...cartItem, quantity: cartItem.quantity - 1 }
            : cartItem
        )
      }));
    }
  };

  const calculateItemPrice = (item) => {
    return item.price * item.quantity;
  };

  const calculateTotalPrice = () => {
    return state.cart.reduce((total, item) => total + calculateItemPrice(item), 0);
  };

  const payNow = (event) => {
    event.preventDefault();
    const options = {
      key: 'rzp_test_Mp5DjD6SGoo7Fk',
      amount: calculateTotalPrice() * 100,
      name: 'Hunger Saviour',
      description: 'Hunger Saviour Razorpay',
      image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPp1ohLNn2RGU2lTyfORSITnkv7U8Jci4oCa-5T1DfFc5JpagoQkZ6imLo-_vrE3aJw10&usqp=CAUhttps://i.imgur.com/FApqk3D.jpeg',

      handler(response) {
        const paymentId = response.razorpay_payment_id;
        axios.post('http://localhost:8765/payments',{
                userName: username,
                transactionId: paymentId,
                amountPaid: calculateTotalPrice()
            })
            .then(res => {
                if(res.status === 201){
                    navigate('/orders');
                }
            })
            .catch(error => {
                console.error('Error in while doing payment:', error);
            });
        clearCart();
      },

      prefill: {
        name: 'Srinivas Basha',
        email: 'dssrinivas02@gmail.com',
        phone: '6303010397',
      },
      notes: {
        address: 'Hyderabad,India',
      },
      theme: {
        color: '#14213d',
      },
    };
    const rzp1 = new window.Razorpay(options);

    rzp1.open();
  };

  return (
    <div className="container cart-container mt-5 pt-5">
      {state.cart.length === 0 ? (
        <div className="d-flex align-items-center justify-content-center">
          <img src="https://www.vhv.rs/dpng/d/521-5212497_empty-cart-hd-png-download.png" alt="Empty Cart" />
        </div>
      ) : (
        <>
          {state.cart.map((item, index) => (
            <div key={index} className="cart-item-container">
              <div className="cart-item-image mb-2" style={{ maxWidth: '150px', overflow: 'hidden' }}>
                <div className="fw-bolder text-truncate">{item.menuItem}</div>
                <img src={item.menuImageUrl} alt={item.menuImageUrl} style={{ width: '100%', height: 'auto' }} />
              </div>
              <div className="cart-item-details">
                <div className="fw-bolder">₹{item.price}</div>
                <div className="item-price fw-bold">
                  Total Price: Rs.{calculateItemPrice(item).toFixed(2)}
                </div>
              </div>
              <div className="item-actions">
                <div className="cart-item-actions">
                  <button className="btn btn-success" style={{ backgroundColor: '#FC8019', borderColor: '#FC8019' }} type="button" onClick={() => decreaseQuantity(item)}>
                    <span className='fw-bold'>-</span>
                  </button>
                  <span className="quantity p-1 fw-bolder">{item.quantity}</span>
                  <button className="btn btn-success" type="button" style={{ backgroundColor: '#FC8019', borderColor: '#FC8019' }} onClick={() => increaseQuantity(item)}>
                  <span className='fw-bold'>+</span>
                  </button>
                </div>
                <button className="btn btn-icon" onClick={() => removeFromCart(item)}>
                  <span className="material-icons">delete</span>
                </button>
              </div>
            </div>
          ))}
          <div className="d-flex justify-content-center mb-4">
            <button className="btn btn-danger m-2" type="button" style={{ backgroundColor: '#FC8019', borderColor: '#FC8019' }} onClick={payNow}>
              Checkout
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export default Cart;
