// Notes/Hunger Saviour/hunger-saviour-portal-angular-main/src/app/dashboard/restaurant/restaurant-menu/restaurant-menu.component.ts
import { Component, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Observable, pluck, tap } from 'rxjs';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Restaurant } from 'src/app/model/Restaurant';
import { RestaurantMenu } from 'src/app/model/RestaurantMenu';
import { trigger, transition, style, animate, stagger, query } from '@angular/animations';
import { CartService } from '../../cart/services/cart.service';

@Component({
  selector: 'app-restaurant-menu',
  templateUrl: './restaurant-menu.component.html',
  styleUrls: ['./restaurant-menu.component.scss'],
  animations: [
    trigger('itemAnimation', [
      transition(':enter', [
        query(':self', [style({ opacity: 0, transform: 'translateY(-30px)' })]),
        query(':self', [
          stagger('500ms', [
            animate('500ms ease-in', style({ opacity: 1, transform: 'translateY(0)' }))
          ])
        ])
      ])
    ])
  ]
})
export class RestaurantMenuComponent implements OnDestroy {

  rest$?: Observable<Restaurant | null>;
  totalCartPrice: number = 0;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private _snackBar: MatSnackBar,
    private cartService: CartService
  ) {
    this.openSnackBar();
  }

  ngOnInit() {
    this.rest$ = this.route.data.pipe(pluck('rest'));
    this.rest$.subscribe(v => console.log("hi", v));
    console.log("Menu component", this.totalCartPrice);
  }

  ngOnDestroy(): void {
    this._snackBar.dismiss();
  }

  addToCart(menu: RestaurantMenu, restaurantId: number) {
    menu.quantity = menu.quantity ? menu.quantity + 1 : 1;
    menu.restaurantId=restaurantId;
    this.cartService.addToCart(menu);
    this.updateTotalPrice();
    this.openSnackBar();
  }

  increaseQuantity(menu: RestaurantMenu) {
    menu.quantity = menu.quantity ? menu.quantity + 1 : 1;
    this.cartService.updateCart(menu);
    this.updateTotalPrice();
  }

  decreaseQuantity(menu: RestaurantMenu) {
    if (menu.quantity && menu.quantity > 0) {
      menu.quantity--;
      this.cartService.updateCart(menu);
      this.updateTotalPrice();
    } else {
      this._snackBar.dismiss();
    }
  }

  updateTotalPrice() {
    this.rest$!.pipe(
      tap(restaurant => {
        if (restaurant && restaurant.menuItems) {
          this.totalCartPrice = restaurant.menuItems.reduce((total, item) => total + item.price * (item.quantity || 0), 0);
        }
      })
    ).subscribe();
    this.openSnackBar();
  }

  openSnackBar() {
    if (this.totalCartPrice > 0) {
      this._snackBar.open(`Total Price: Rs.${this.totalCartPrice.toFixed(2)}`, 'View Cart')
        .onAction().subscribe(() => {
          // Handle the action (e.g., navigate to the cart page)
          this.router.navigateByUrl('dashboard/cart');
        });
    } else {
      // If totalCartPrice is zero, close the snackbar
      this._snackBar.dismiss();
    }
  }
}
<ng-container *ngIf="rest$ | async as restaurant">
  <div *ngIf="restaurant.menuItems">
    <div
      *ngFor="let menu of restaurant.menuItems"
      class="container d-flex flex-wrap align-items-center justify-content-center my-2"
      [@itemAnimation]
    >
      <div class="col-lg-7">
        <div class="d-flex flex-column">
          <div class="fw-bolder">{{ menu.itemName }}</div>
          <div class="fw-bolder">{{ menu.price }}</div>
          <div class="d-flex flex-row fw-bold">
            <mat-icon class="ratingicon">stars</mat-icon
            >{{ restaurant?.rating }}
          </div>
          <div class="text-secondary custom-scroll m-1">
            {{ menu.description | slice : 0 : 150 }}

            <!-- Use *ngIf to show "show more" link only if description length exceeds a certain limit -->
            <ng-container *ngIf="menu.description.length > 100">
              <span *ngIf="!menu.showFullDescription">
                <!-- "Show more" link -->
                <a
                  href="javascript:void(0)"
                  (click)="menu.showFullDescription = true"
                  class="show fw-bold"
                >
                  Show more</a
                >
              </span>
              <span *ngIf="menu.showFullDescription">
                <!-- Full description -->
                {{ menu.description }}
                <!-- "Show less" link -->
                <a
                  href="javascript:void(0)"
                  (click)="menu.showFullDescription = false"
                  class="show fw-bold"
                >
                  Show less</a
                >
              </span>
            </ng-container>
          </div>
          <div class="text-secondary fw-bold">{{ menu.menuType }}</div>
        </div>
      </div>

      <div class="col-lg-3">
        <div class="card-image-container position-relative">
          <img
            mat-card-image
            [src]="menu.menuImageUrl"
            alt="{{ menu.menuImageUrl }}"
          />
        </div>
      </div>

      <div class="col-lg-2">
        <mat-card class="restaurant-card no-shadow">
          <div
            class="card-image-container d-flex flex-wrap align-items-center justify-content-center"
          >
            <div *ngIf="menu.quantity > 0">
              <!-- Quantity control -->
              <div class="quantity-control d-flex align-items-center">
                <button
                  (click)="decreaseQuantity(menu)"
                  mat-raised-button
                  color="primary"
                  class="fw-bold text-light m-2"
                >
                  -
                </button>
                <div class="quantity fw-bold text-muted">
                  {{ menu.quantity }}
                </div>
                <button
                  (click)="increaseQuantity(menu)"
                  mat-raised-button
                  color="primary"
                  class="fw-bold text-light m-2"
                >
                  +
                </button>
              </div>
            </div>
            <ng-container *ngIf="menu.quantity === 0 || !menu.quantity">
              <!-- Add to Cart button -->
              <button
                (click)="addToCart(menu,restaurant.restaurantId)"
                mat-raised-button
                color="primary"
                class="fw-bold text-light"
              >
                Add To Cart
              </button>
            </ng-container>
          </div>
        </mat-card>
      </div>
    </div>
  </div>
</ng-container>

// Notes/Hunger Saviour/hunger-saviour-portal-react-main/src/components/RestaurantMenu.js
// RestaurantMenu.js
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useParams } from 'react-router-dom';
import StarsIcon from '@mui/icons-material/Stars';
import { useAppContext } from '../AppContext';

function RestaurantMenu() {
  const { restaurantId } = useParams();
  const [expandedDescriptions, setExpandedDescriptions] = useState([]);
  const [menuItems, setMenuItems] = useState([]);
  const { state, setState } = useAppContext();

  useEffect(() => {
    axios.get(`http://localhost:8765/restaurants/${restaurantId}`)
      .then(res => {
        const menuItemsData = res.data.menuItems || [];
        setMenuItems(menuItemsData);
        setExpandedDescriptions(Array(menuItemsData.length).fill(false));
      })
      .catch(error => {
        console.error('Error fetching restaurants:', error);
      });
  }, [restaurantId]);

  const toggleDescription = (index) => {
    setExpandedDescriptions(prevState => {
      const newState = [...prevState];
      newState[index] = !newState[index];
      return newState;
    });
  };

  const addToCart = (menuItem) => {
    // Clear the cart if the restaurant ID of the new item is different
    if (state.cart.length > 0 && state.cart[0].restaurantId !== restaurantId) {
      setState(prevState => ({
        ...prevState,
        cart: []
      }));
    }

    const existingItemIndex = state.cart.findIndex(item => item.menuItem === menuItem.menuItem);
  
    if (existingItemIndex !== -1) {
      // If the item already exists in the cart, update its quantity
      const updatedCart = [...state.cart];
      updatedCart[existingItemIndex].quantity++;
      setState(prevState => ({
        ...prevState,
        cart: updatedCart
      }));
    } else {
      // If the item does not exist in the cart, add it with quantity 1
      setState(prevState => ({
        ...prevState,
        cart: [...prevState.cart, { ...menuItem, quantity: 1, restaurantId }]
      }));
    }
  };

  const increaseQuantity = (menuItem) => {
    setState(prevState => ({
      ...prevState,
      cart: prevState.cart.map(cartItem =>
        cartItem.menuItem === menuItem.menuItem
          ? { ...cartItem, quantity: cartItem.quantity + 1 }
          : cartItem
      )
    }));
  };

  const decreaseQuantity = (menuItem) => {
    const existingItem = state.cart.find(item => item.menuItem === menuItem.menuItem);
    if (existingItem && existingItem.quantity === 1) {
      // If quantity is 1, remove the item from the cart
      const updatedCart = state.cart.filter(item => item.menuItem !== menuItem.menuItem);
      setState(prevState => ({
        ...prevState,
        cart: updatedCart
      }));
    } else {
      setState(prevState => ({
        ...prevState,
        cart: prevState.cart.map(cartItem =>
          cartItem.menuItem === menuItem.menuItem && cartItem.quantity > 1
            ? { ...cartItem, quantity: cartItem.quantity - 1 }
            : cartItem
        )
      }));
    }
  };

  return (
    <div className='mt-5 pt-3'>
      {/* Render restaurant menus */}
      {menuItems &&
        menuItems.map((menuItem, index) => (
          <div key={menuItem.restaurantMenuId} className="container d-flex flex-wrap align-items-center justify-content-center my-2">
            <div className="col-lg-7">
              <div className="d-flex flex-column">
                <div className="fw-bolder">{menuItem.menuItem}</div>
                <div className="fw-bolder">{menuItem.price}</div>
                <div className="d-flex flex-row fw-bold">
                  <span style={{ color: '#60b246' }}><StarsIcon /></span>
                  4.2
                </div>
                <div className="text-secondary custom-scroll m-1">
                  {expandedDescriptions[index] ? menuItem.description : menuItem.description.slice(0, 150)}
                  {menuItem.description.length > 100 && (
                    <span>
                      <a href="#!" onClick={() => toggleDescription(index)} className="show fw-bold" style={{ color: '#FC8019' }}>
                        {expandedDescriptions[index] ? "Show less" : "Show more"}
                      </a>
                    </span>
                  )}
                </div>
                <div className="text-secondary fw-bold">{menuItem.menuType}</div>
              </div>
            </div>

            <div className="col-lg-3">
              <div className="card-image-container position-relative">
                <img src={menuItem.menuImageUrl} alt={menuItem.menuImageUrl} className="menu-image" />
              </div>
            </div>

            <div className="col-lg-2">
              <div className="restaurant-card no-shadow">
                <div className="card-image-container d-flex flex-wrap align-items-center justify-content-center">
                  {/* Show item quantity with buttons */}
                  {state.cart.some(item => item.menuItem === menuItem.menuItem) ? (
                    <div className="quantity">
                      <button className="btn btn-success" type="button" style={{ backgroundColor: '#FC8019', borderColor: '#FC8019' }} onClick={() => decreaseQuantity(menuItem)}><span className='fw-bold'>-</span></button>
                      <span className='p-2 fw-bolder'>{state.cart.find(item => item.menuItem === menuItem.menuItem).quantity}</span>
                      <button className="btn btn-success" type="button" style={{ backgroundColor: '#FC8019', borderColor: '#FC8019' }} onClick={() => increaseQuantity(menuItem)}><span className='fw-bold'>+</span></button>
                    </div>
                  ) : (
                    // Show "Add to Cart" button if item is not in the cart
                    <button className="btn btn-success" type="button" style={{ backgroundColor: '#FC8019', borderColor: '#FC8019' }} onClick={() => addToCart(menuItem)}>
                      Add To Cart
                    </button>
                  )}
                </div>
              </div>
            </div>
          </div>
        ))}
    </div>
  );
}

export default RestaurantMenu;
